### ISSUE TITLE
Podcast page breaks if feed has only 1 link in "links" object

### ISSUE THREAD

**Issue by Zedex7** [Bhupesh-V/defe#12]
**Describe the bug**
Podcast page breaks if feed has only 1 link in "links" object

**To Reproduce**
1. Go to 'Home'
2. Click on 'Feed>Podcasts'

**Expected behavior**
Podcast page should open and feed should be visible with working audio player.

**Screenshots**
![image](https://user-images.githubusercontent.com/14003108/85063057-2e342900-b1c7-11ea-91ab-88be8abc305a.png)

![image](https://user-images.githubusercontent.com/14003108/85063752-38a2f280-b1c8-11ea-9c76-a72514f70438.png)

**Comment by Zedex7** [comment]
Hey @Bhupesh-V, I think of fix would be to filter out non mp3 links based on `item["links"].["type"] == "audio/mpeg"` in `feedcore.podcasts_feeds()` after `fetcher()` call and change `item.links[0].href` in template file.

Let me know, if I can raise Pull Request for this small contribution.

**Comment by Bhupesh-V** [comment]
> Let me know, if I can raise Pull Request for this small contribution.

Sure @Zedex7 you can create a PR

**Comment by Bhupesh-V** [comment]
@all-contributors please add @Zedex7  for bug and code
