### ISSUE TITLE
Dark Mode not remembering state

### ISSUE THREAD

**Issue by Bhupesh-V** [Bhupesh-V/defe#2]
I am currently using `darkmode.js` for this.

**Comment by arunaaabh95** [comment]
Hi
this is an issue with darkmode.js itself
you can check their sample websites here: https://tradivegan.com (link is posted in npm library page: https://www.npmjs.com/package/darkmode-js)
also it works fine for firefox but funny thing is they are adding darkmode to the scroll bar in my case
I would suggest implementing our own dark mode I would like to work on this if possible

**Comment by Bhupesh-V** [comment]
Thanks @arunaaabh95 for pointing that out, I think implementing our own dark mode would be a nice idea :bulb: 
Let me open a separate issue for this, then you can start working

**Comment by Bhupesh-V** [comment]
@arunaaabh95 you can start working now, good luck :+1:

**Comment by arunaaabh95** [comment]
Hi,
here is my pr [https://github.com/Bhupesh-V/defe/pull/6](url)
