### ISSUE TITLE
Typo in podcasts.json

### ISSUE THREAD

**Issue by AyushRawal** [Bhupesh-V/defe#22]
There is a small typo in podcasts.json
'Software Defined Talk' has been mentioned twice.
The second one should be 'Soft Skills Engineering'.

**Comment by Bhupesh-V** [comment]
@AyushRawal Thanks for reporting this 👍🏽 🔥

**Comment by Bhupesh-V** [comment]
@all-contributors please add @AyushRawal  for bug
