### ISSUE TITLE
Changes is template not reflecting while testing

### ISSUE THREAD

**Issue by arunaaabh95** [Bhupesh-V/defe#5]
**Describe the bug**
When I make changes to templates eg(base.html) the changes do not reflect while testing

**To Reproduce**
1. make changes to file (eg base.html) will not happen for home.html
2. reload localhost
3 new changes not reflected

**Expected behavior**
Should be able to see new changes

**Probable Solution**
In `app.py` we should watch for template files which are not loaded via render_template function
Reference: https://stackoverflow.com/questions/9508667/reload-flask-app-when-template-file-changes

**Comment by Bhupesh-V** [comment]
Have you tried adding `TEMPLATES_AUTO_RELOAD = True` in `.flaskenv` ?
I think this might solve the problem.

**Comment by arunaaabh95** [comment]
actually I found that my browser was caching the old templates. Nevertheless should I create a pr for this or is this intentional? (no ``TEMPLATES_AUTO_RELOAD = True`` in flask.env)

**Comment by Bhupesh-V** [comment]
> actually I found that my browser was caching the old templates.

I think this is happening because of Service Worker`SW.js`, I will work on a fix for that
If you want you can add `TEMPLATES_AUTO_RELOAD` in your PR

**Comment by arunaaabh95** [comment]
added this in darkmode fix 
[https://github.com/Bhupesh-V/defe/pull/6](url)
