### ISSUE TITLE
Play Podcasts in terminal

### ISSUE THREAD

**Issue by Bhupesh-V** [Bhupesh-V/defe#7]
Download Podcasts locally and ask user to play them.
Better if we can stream it
Look for `playsound` packages in Python

**Comment by Bhupesh-V** [comment]
After a bit of researching. I think using vlc for this would be a wise choice (since it is available on different OS)

Here is a sample code on how `pytthon-vlc` package can be used

```python
import vlc
p = vlc.MediaPlayer("https://chtbl.com/track/33225/aphid.fireside.fm/d/1437767933/bc7f1faf-8aad-4135-bb12-83a8af679756/1555ba4d-39b0-406c-8023-23cc3814c357.mp3")
p.play()
# p.pause()
# p.stop()
```

**Comment by Svn-Sp** [comment]
Sounds really interesting, I would like to work on this

**Comment by AyushRawal** [comment]
I think mpv would be a better idea for the player.
It has proper command line interface.

**Comment by Bhupesh-V** [comment]
> I think mpv would be a better idea for the player.
> It has proper command line interface.

Hi, @AyushRawal thanks for your suggestion 👍🏽 . It looks like installing mpv's python API is a pain in Windows.
Whereas it is pretty straight forward in VLC.
