### ISSUE TITLE
Media notification for the PWA

### ISSUE THREAD

**Issue by Bhupesh-V** [Bhupesh-V/defe#9]
[Media Notification](https://developers.google.com/web/updates/2017/02/media-session) - for podcasts

Starter code inside `script.js`
https://github.com/Bhupesh-V/defe/blob/5b2db4a39ddd5ecf20d4397709eaa2c459ea83e1/static/script.js#L130-L137

**Comment by Zedex7** [comment]
Hey @Bhupesh-V , I can work on this. Please assign me.

**Comment by Bhupesh-V** [comment]
Sure @Zedex7

**Comment by ovielma** [comment]
Hello, I noticed nobody was working on this so I went ahead and gave it a shot! I think I have a working solution ready but I noticed the build is failing and website is down. I'll hold off on submitting a PR until this has been resolved so I can properly test what I added :)

**Comment by Bhupesh-V** [comment]
> Hello, I noticed nobody was working on this so I went ahead and gave it a shot! I think I have a working solution ready but I noticed the build is failing and website is down. I'll hold off on submitting a PR until this has been resolved so I can properly test what I added :)

Hi @ovielma 👋🏽 
Looks like the webapp is up now, you can send a PR
